// Applies SQL migrations from ./drizzle with readable errors. Runs before every Vercel build.
import { writeFileSync } from "node:fs";
import { config } from "dotenv";
import { createClient } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import { migrate } from "drizzle-orm/libsql/migrator";
import { clean, URL_VARS, TOKEN_VARS } from "./db-env.mjs";

config({ path: ".env.local", quiet: true });

const hostOf = (url) => {
  if (url.startsWith("file:")) return url;
  try {
    return new URL(url.replace(/^libsql:/, "https:")).host;
  } catch {
    return "(unparseable URL)";
  }
};

/** Send one tiny query over HTTP to surface Turso's real error message. */
async function probe(url, token) {
  if (url.startsWith("file:")) return { ok: true };
  try {
    const res = await fetch(url.replace(/^libsql:\/\//, "https://").replace(/\/+$/, "") + "/v2/pipeline", {
      method: "POST",
      headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) },
      body: JSON.stringify({ requests: [{ type: "execute", stmt: { sql: "select 1" } }, { type: "close" }] }),
    });
    const body = (await res.text()).slice(0, 300);
    const failed = !res.ok || /"type":"error"/.test(body);
    return failed ? { ok: false, detail: `HTTP ${res.status} ${token ? body.split(token).join("<token>") : body}` } : { ok: true };
  } catch (err) {
    return { ok: false, detail: err?.cause?.message ?? err?.message };
  }
}

const urls = URL_VARS.filter((v) => clean(process.env[v]));
const tokens = TOKEN_VARS.filter((v) => clean(process.env[v]));

if (!urls.length) {
  if (process.env.VERCEL) {
    console.error(
      "✖ No database configured. Set DATABASE_URL and DATABASE_AUTH_TOKEN (or TURSO_DATABASE_URL and TURSO_AUTH_TOKEN) " +
        "in Vercel → Settings → Environment Variables for this environment, then redeploy.",
    );
    process.exit(1);
  }
  console.log("No DATABASE_URL set; skipping migrations (local dev uses `npm run db:push`).");
  process.exit(0);
}

// Try matching pairs first (DATABASE_URL+DATABASE_AUTH_TOKEN, TURSO_*+TURSO_*), then cross combinations.
const pairs = [];
for (let i = 0; i < URL_VARS.length; i++) {
  const u = URL_VARS[i];
  if (!urls.includes(u)) continue;
  const same = TOKEN_VARS[i];
  if (tokens.includes(same)) pairs.push([u, same]);
}
for (const u of urls) for (const t of [...tokens, null]) if (!pairs.some(([a, b]) => a === u && b === t)) pairs.push([u, t]);

let chosen = null;
for (const [urlVar, tokenVar] of pairs) {
  const url = clean(process.env[urlVar]);
  const token = tokenVar ? clean(process.env[tokenVar]) : undefined;
  const r = await probe(url, token);
  console.log(`${r.ok ? "✓" : "✖"} ${urlVar} (${hostOf(url)}) + ${tokenVar ?? "no token"}${r.ok ? "" : ` → ${r.detail}`}`);
  if (r.ok) {
    chosen = { urlVar, tokenVar };
    break;
  }
}

if (!chosen) {
  console.error("✖ No URL/token combination was accepted by the database. See the errors above.");
  console.error("  Fix: in Vercel, make sure the URL and token come from the SAME Turso database, or delete the extra pair.");
  process.exit(1);
}

console.log(`→ Using ${chosen.urlVar} + ${chosen.tokenVar ?? "no token"}`);
if (process.env.VERCEL) {
  writeFileSync(
    new URL("./db-choice.generated.mjs", import.meta.url),
    `// Generated by scripts/migrate.mjs. Env var names only, never values.\nexport const choice = ${JSON.stringify(chosen)};\n`,
  );
}

const client = createClient({
  url: clean(process.env[chosen.urlVar]),
  authToken: chosen.tokenVar ? clean(process.env[chosen.tokenVar]) : undefined,
});
try {
  await migrate(drizzle(client), { migrationsFolder: "./drizzle" });
  console.log("✓ Migrations applied");
} catch (err) {
  console.error(`✖ Migration failed: ${[err?.message, err?.cause?.message].filter(Boolean).join(" | ")}`);
  process.exit(1);
} finally {
  client.close();
}
